vim.api.nvim_create_user_command('CompileAndRun', function()
    vim.cmd("w")
    vim.cmd("split")
    vim.cmd("wincmd j")
    vim.cmd("resize 8")
    vim.cmd("term g++ -std=c++17 % && ./a.out")
end, {})
vim.keymap.set("n", "<F6>" , ":CompileAndRun<CR>", {})
